### ISSUE TITLE
Remove LethalConfig dependency

### ISSUE THREAD

**Issue by MJHeijster** [Schnabelborg/LethalFlashlights#1]
I like having this mod, but I don't really see why LethalConfig is a dependency. Can you please remove the dependency?

**Comment by Schnabelborg** [comment]
I understand your confusion, since, of course, LethalConfig is _just_ used as a quality-of-life feature.

But because it let's you configure the chance of explosion directly in the game without having to restart or open up the config file, I'd rather not remove it, as LethalConfig is used in the code and the feature would then have to be removed entirely.
